-- Migration 046: seed procurement packaging configuration from design/Opening Stock 20-Jul-2026.pdf
--
-- Source: IaC/design/Opening Stock 20-Jul-2026.pdf ("STOCK AT GODOWN" report, 4 pages, 41
-- numbered brand entries). This is a THREE-TABLE seed because a "packaging configuration"
-- ties a brand+technical (procurement.technicals) to a pack size (procurement.packaging_meta)
-- via the join table procurement.packagings:
--   1. procurement.technicals   — upsert (technical_name, brand_name) pairs, ON CONFLICT
--      (technical_name) — the table's only unique constraint (migration 026). Existing rows
--      are matched/reused by brand_name wherever possible (see notes below) rather than
--      re-inserted, since technical_name text varies slightly release-to-release (spacing,
--      "W/W" suffixes, typos already baked into the migration 028 seed) and technical_name
--      collisions would make a duplicate INSERT silently no-op under ON CONFLICT.
--   2. procurement.packaging_meta — upsert (unit_type, label) pack-size rows, ON CONFLICT
--      (unit_type, label) — same pattern as migration 034. All sizes found in this report
--      already exist from migration 034's "Opening Stock 15-Jul-2026.pdf" seed, EXCEPT two
--      new IMIX-specific variants: '8 GM (P)' and '8 GM (T)'.
--   3. procurement.packagings — for each (brand, size) pair, INSERT ... SELECT joining
--      technicals.id + packaging_meta.id by brand_name/label, ON CONFLICT (technical_id,
--      packaging_meta_id) DO NOTHING (migration 035's unique constraint). Robust whether the
--      technicals/packaging_meta row was just inserted above or already existed.
--
-- Report row interpretation: each PACKING cell looks like "10X1 KG" — the leading "10X" is
-- the outer case-pack count (cases per carton) and is IGNORED; the trailing AP/TS columns are
-- current stock quantities and are also IGNORED. Only the per-unit pack size after the "X"
-- (e.g. "1 KG", "500 GM", "250 ML") is captured here. The report is grouped by numbered brand
-- entry (S No + brand name), with the technical/active-ingredient name printed as a wrapped
-- multi-line cell below the brand, and one PACKING/AP/TS row per pack size — that grouping is
-- how each brand's technical composition was determined (all 41 entries had a derivable
-- technical name; see the IaC-agent report for the full extraction detail).
--
-- Brand-matching notes (existing procurement.technicals rows, from migration 028, are reused
-- rather than duplicated):
--   - 38 of 41 report brands match an EXISTING technicals.brand_name EXACTLY — no new
--     technicals row is inserted for them; the packagings INSERT below looks them up by
--     brand_name directly.
--   - 'GUNSHOT' (report) is treated as the existing 'GUN SHOT' brand (spacing variant only;
--     same technical composition FIPRONIL 40%+IMIDACLOPRID 40% WG) — reused via brand_name
--     'GUN SHOT', not re-inserted.
--   - 'I-TAF PLUS' (report) is treated as the existing 'I-TAFPLUS' brand (spacing variant
--     only; same technical HEXACONAZOLE 5% SC) — reused via brand_name 'I-TAFPLUS'.
--   - 'HUNTER' and 'GULFONID' are genuinely NEW brands (no existing technicals row) — new
--     technicals rows are inserted for them below. Neither collides with an existing
--     technical_name string, so the INSERT is safe (not silently swallowed by ON CONFLICT).
--   - 'GROMAX' (report brand #10, technical "GIBBERELLIC ACID 0.001% L") is DELIBERATELY
--     EXCLUDED from this migration: its derived technical_name is a byte-for-byte match of
--     the EXISTING technicals row already owned by brand 'CHIEF' (migration 028). Since
--     technical_name is the table's only unique constraint, inserting a second row for GROMAX
--     with the identical technical_name would silently no-op under ON CONFLICT, leaving GROMAX
--     without its own technicals row and orphaning any packagings insert keyed off it — rather
--     than guess whether GROMAX/CHIEF are the same product under two commercial names or a
--     genuine data conflict, it is flagged here and left out. No technicals or packagings rows
--     are created for GROMAX by this migration.
--
-- Idempotent, non-destructive (no DELETE/TRUNCATE). Applied MANUALLY via psql over the SSM
-- bastion tunnel (see migration 026 header for the connection command). Requires 026 (schema),
-- 028 (technicals seed), 033/034 (packaging_meta), and 035 (packagings) already applied.

BEGIN;

-- ── 1. technicals — new brands only (no collision with an existing technical_name) ──────────
INSERT INTO procurement.technicals (technical_name, brand_name) VALUES ('EMAMECTIN BENZOATE 5% SG', 'HUNTER') ON CONFLICT (technical_name) DO NOTHING;
INSERT INTO procurement.technicals (technical_name, brand_name) VALUES ('GLUFOSINATE AMMONIUM 13.5 % W/W SL', 'GULFONID') ON CONFLICT (technical_name) DO NOTHING;

-- ── 2. packaging_meta — new pack sizes only (IMIX barcoded pouch/tin variants) ───────────────
INSERT INTO procurement.packaging_meta (unit_type, label, sort_order) VALUES
  ('KG', '8 GM (P)', 121),
  ('KG', '8 GM (T)', 122)
ON CONFLICT (unit_type, label) DO NOTHING;

-- ── 3. packagings — brand+size links (all 40 usable report brands; GROMAX excluded) ─────────
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'KG' AND m.label = '1 KG' WHERE t.brand_name = 'ACEPRIDE' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'KG' AND m.label = '500 GM' WHERE t.brand_name = 'ACEPRIDE' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'KG' AND m.label = '250 GM' WHERE t.brand_name = 'ACEPRIDE' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'KG' AND m.label = '100 GM' WHERE t.brand_name = 'ACEPRIDE' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'KG' AND m.label = '100 GM (B)' WHERE t.brand_name = 'ACEPRIDE' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'KG' AND m.label = '50 GM' WHERE t.brand_name = 'ACEPRIDE' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'KG' AND m.label = '50 GM BOX' WHERE t.brand_name = 'ACEPRIDE' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '1 LT' WHERE t.brand_name = 'AGENT' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '500 ML' WHERE t.brand_name = 'AGENT' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '250 ML' WHERE t.brand_name = 'AGENT' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '1 LT' WHERE t.brand_name = 'ASTODIA' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '500 ML' WHERE t.brand_name = 'ASTODIA' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '250 ML' WHERE t.brand_name = 'ASTODIA' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '250 ML' WHERE t.brand_name = 'AVACIN' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '100 ML' WHERE t.brand_name = 'AVACIN' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '1400 ML' WHERE t.brand_name = 'CALARIS GOLD' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '700 ML' WHERE t.brand_name = 'CALARIS GOLD' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '500 ML' WHERE t.brand_name = 'CLEAN' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '250 ML' WHERE t.brand_name = 'CLEAN' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '1 LT' WHERE t.brand_name = 'DHAMAKA' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '500 ML' WHERE t.brand_name = 'DHAMAKA' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '250 ML' WHERE t.brand_name = 'DHAMAKA' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'KG' AND m.label = '133.2 GM' WHERE t.brand_name = 'FLYSTAR' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '1 LT' WHERE t.brand_name = 'GENSTAR' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '500 ML' WHERE t.brand_name = 'GENSTAR' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '250 ML' WHERE t.brand_name = 'GENSTAR' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '500 ML' WHERE t.brand_name = 'GULFONID' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '500 ML' WHERE t.brand_name = 'GULFPLUS' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '250 ML' WHERE t.brand_name = 'GULFPLUS' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'KG' AND m.label = '250 GM' WHERE t.brand_name = 'GUN SHOT' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'KG' AND m.label = '100 GM' WHERE t.brand_name = 'GUN SHOT' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'KG' AND m.label = '40 GM' WHERE t.brand_name = 'GUN SHOT' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'KG' AND m.label = '500 GM' WHERE t.brand_name = 'HUNTER' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'KG' AND m.label = '250 GM' WHERE t.brand_name = 'HUNTER' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'KG' AND m.label = '100 GM' WHERE t.brand_name = 'HUNTER' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'KG' AND m.label = '50 GM' WHERE t.brand_name = 'HUNTER' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '100 ML' WHERE t.brand_name = 'I-PHON' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '1 LT' WHERE t.brand_name = 'I-STAR' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '500 ML' WHERE t.brand_name = 'I-STAR' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '250 ML' WHERE t.brand_name = 'I-STAR' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '1 LT' WHERE t.brand_name = 'I-SUPER' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '500 ML' WHERE t.brand_name = 'I-SUPER' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '250 ML' WHERE t.brand_name = 'I-SUPER' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '1 LT' WHERE t.brand_name = 'I-TAFPLUS' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '500 ML' WHERE t.brand_name = 'I-TAFPLUS' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '250 ML' WHERE t.brand_name = 'I-TAFPLUS' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '1 LT' WHERE t.brand_name = 'I-TOP' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '500 ML' WHERE t.brand_name = 'I-TOP' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '250 ML' WHERE t.brand_name = 'I-TOP' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '150 ML' WHERE t.brand_name = 'I-ZEN' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '60 ML' WHERE t.brand_name = 'I-ZEN' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '30 ML' WHERE t.brand_name = 'I-ZEN' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '10 ML' WHERE t.brand_name = 'I-ZEN' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '230 ML' WHERE t.brand_name = 'IDIS' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '115 ML' WHERE t.brand_name = 'IDIS' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '1 LT' WHERE t.brand_name = 'IMIDAN' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '500 ML' WHERE t.brand_name = 'IMIDAN' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '250 ML' WHERE t.brand_name = 'IMIDAN' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '100 ML' WHERE t.brand_name = 'IMIDAN' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'KG' AND m.label = '8 GM (P)' WHERE t.brand_name = 'IMIX' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'KG' AND m.label = '8 GM (T)' WHERE t.brand_name = 'IMIX' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '1 LT' WHERE t.brand_name = 'IMPLIGO' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '500 ML' WHERE t.brand_name = 'IMPLIGO' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '200 ML' WHERE t.brand_name = 'IMPLIGO' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '1 LT' WHERE t.brand_name = 'IRA GOLD' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '500 ML' WHERE t.brand_name = 'IRA GOLD' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '200 ML' WHERE t.brand_name = 'IRA GOLD' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '100 ML' WHERE t.brand_name = 'IRA GOLD' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'KG' AND m.label = '1 KG' WHERE t.brand_name = 'ITARA' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'KG' AND m.label = '250 GM' WHERE t.brand_name = 'ITARA' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'KG' AND m.label = '100 GM' WHERE t.brand_name = 'ITARA' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'KG' AND m.label = '100 GM' WHERE t.brand_name = 'LAVA' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '1 LT' WHERE t.brand_name = 'MALLIKA' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '500 ML' WHERE t.brand_name = 'MALLIKA' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '250 ML' WHERE t.brand_name = 'MALLIKA' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '1 LT' WHERE t.brand_name = 'NOMA' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '500 ML' WHERE t.brand_name = 'NOMA' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '250 ML' WHERE t.brand_name = 'NOMA' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '1 LT' WHERE t.brand_name = 'NOVAN' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '500 ML' WHERE t.brand_name = 'NOVAN' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '250 ML' WHERE t.brand_name = 'NOVAN' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '1 LT' WHERE t.brand_name = 'OBERA' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '500 ML' WHERE t.brand_name = 'OBERA' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '200 ML' WHERE t.brand_name = 'OBERA' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '100 ML' WHERE t.brand_name = 'OBERA' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '500 ML' WHERE t.brand_name = 'PERMAKILL' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '250 ML' WHERE t.brand_name = 'PERMAKILL' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '100 ML' WHERE t.brand_name = 'PERMAKILL' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '1 LT' WHERE t.brand_name = 'RADIATOR' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '500 ML' WHERE t.brand_name = 'RADIATOR' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '250 ML' WHERE t.brand_name = 'RADIATOR' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'KG' AND m.label = '500 GM' WHERE t.brand_name = 'RIM' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'KG' AND m.label = '250 GM' WHERE t.brand_name = 'RIM' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'KG' AND m.label = '125 GM' WHERE t.brand_name = 'RIM' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '1 LT' WHERE t.brand_name = 'SUPER IMIDAN' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '500 ML' WHERE t.brand_name = 'SUPER IMIDAN' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '250 ML' WHERE t.brand_name = 'SUPER IMIDAN' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '1 LT' WHERE t.brand_name = 'TARGASTAR' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '500 ML' WHERE t.brand_name = 'TARGASTAR' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '250 ML' WHERE t.brand_name = 'TARGASTAR' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '1 LT' WHERE t.brand_name = 'TIGER' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '250 ML' WHERE t.brand_name = 'TIGER' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'KG' AND m.label = '120 GM' WHERE t.brand_name = 'TRAIL' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'KG' AND m.label = '1 KG' WHERE t.brand_name = 'VITARA' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'KG' AND m.label = '250 GM' WHERE t.brand_name = 'VITARA' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '1 LT' WHERE t.brand_name = 'VIVAYA PLUS' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '1 LT' WHERE t.brand_name = 'WINDOX' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '500 ML' WHERE t.brand_name = 'WINDOX' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '200 ML' WHERE t.brand_name = 'WINDOX' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;
INSERT INTO procurement.packagings (technical_id, packaging_meta_id) SELECT t.id, m.id FROM procurement.technicals t JOIN procurement.packaging_meta m ON m.unit_type = 'LTR' AND m.label = '100 ML' WHERE t.brand_name = 'WINDOX' ON CONFLICT (technical_id, packaging_meta_id) DO NOTHING;

COMMIT;
